name: Run SSH Commands

on:
  push:
    branches:
      - master
    paths:
      - sshdata/**

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --accept-routes --authkey ${{ secrets.TAILSCALE_KEY }}

      - name: Setup SSH
        run: |
          mkdir ~/.ssh && touch ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa && chmod 700 ~/.ssh

      - name: Set SSH Key
        run: 'echo "$SSH_KEY" > ~/.ssh/id_rsa'
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVKEY }}

      - name: Run SSH commands
        run: |
          cat $GITHUB_WORKSPACE/sshdata/test.sh | ssh -o "StrictHostKeyChecking=no" vcokltfre@10.1.1.132 -i ~/.ssh/id_rsa
